# PostgreSQL DB config (For production)
spring.datasource.url=jdbc:postgresql://localhost:5432/tripyydb
spring.datasource.username=postgres
spring.datasource.password=0111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
