server.port=8082

# H2 In-Memory DB Config (Default for local running)
spring.datasource.url=jdbc:h2:mem:tripyydb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Logging
logging.level.org.springframework.web=INFO
logging.level.com.tripplanner.backend=DEBUG

# JWT Configuration
jwt.secret=${JWT_SECRET:df89g7sdf89g7sfd89g7sdf89g7sdf89g7sdf89g7sfd89g7sfd89g7s}
jwt.expirationMs=86400000

